### ISSUE TITLE
请问在首页的功能按钮组件里的View外面套了个TouchableWithoutFeedback是为什么

### ISSUE THREAD

**Issue by gantoday** [yuanguozheng/JdApp#5]
你好，谢谢你的教程，让我学到了许多东西。
我是看你的博客 http://blog.csdn.net/yuanguozhengjust/article/details/50601111 学习的。
在这篇博文里，控件是

```
render() {  
    return (  
        <TouchableWithoutFeedback>  
            <View style={{alignItems:'center',flex:1}}>  
                <Image style={styles.iconImg} />  
                <Text>Example Text</Text>  
            </View>  
        </TouchableWithoutFeedback>  
    );  
}
```

请问为什么要在View外面套个 TouchableWithoutFeedback ？ 我看这个 TouchableWithoutFeedback好像也没用到？

**Comment by yuanguozheng** [comment]
@gantoday 这个是为了能让它里面这个View可以点击，WithoutFeedback可以点击，但没有点击效果的

**Comment by gantoday** [comment]
@yuanguozheng 谢谢。刚开始我以为这个东西是你自己命名的呢，原来是react native 自带的。
